language: java
jdk:
  - oraclejdk8
  - oraclejdk10
  - openjdk8
  - openjdk10
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_deploy:
  - ./gradlew sourceJar
  - ./gradlew generatePomFileForMavenPublication
deploy:
  provider: bintray
  file: "bintray.json"
  user: $BINTRAY_API_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true
  on:
    condition: $TRAVIS_TAG = release*