language: java
jdk:
  - oraclejdk8
  - oraclejdk10
  - openjdk8
  - openjdk10
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_deploy:
  - ./gradlew sourceJar
  - ./gradlew generatePomFileForMavenPublication
  - var1=${TRAVIS_TAG#"release-"};sed -i -- "s/{VERSION}/$var1/g" "bintray.json"
deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: build/libs/*
    skip_cleanup: true
    jdk: oraclejdk8
    on:
      tags: true
      condition: $TRAVIS_TAG = release-*
  - provider: bintray
    file: "bintray.json"
    user: $BINTRAY_API_USER
    key: $BINTRAY_API_KEY
    skip_cleanup: true
    jdk: oraclejdk8
    on:
      tags: true
      condition: $TRAVIS_TAG = release-*